[package]
name = "sunlight-api-lab"
version = "0.2.1144"





edition = "2021"

[[bin]]
name = "sunlight-api-lab"
path = "src/main.rs"

[lib]
name = "sunlight_api_lab"
path = "src/lib.rs"

[dependencies]
serde_json = { version = "1", default-features = false, features = ["alloc"] }
sun-font = { path = "../sun-font" }
sunlight-fetch = { path = "../sunlight-fetch", default-features = false, features = ["sunlightos"] }
sunlight-http = { path = "../sunlight-http" }
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
