[package]
name = "sunlight-dict"
version = "0.2.2199-alpha.1"






























































































































































































































































































































































edition = "2021"

[[bin]]
name = "dict"
path = "src/main.rs"

[dependencies]
sunlight-libc = { path = "../../sunlight-libc", features = ["global-alloc"] }
