[package]
name = "rand_service"
version = "0.2.1171"






















































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
