//! Font atlas for framebuffer login screen.
//!
//! Provides anti-aliased text rendering using pre-rasterized glyphs from the
//! SunlightOS UI font (Inter). The atlas is embedded at build time via
//! include_bytes! and uses the same MTF format as sun-font.
//!
//! Key design rules:
//! - Pure no_std, no heap, no external dependencies at runtime
//! - No dependency on sunlight-ui or the display service
//! - Alpha blending for anti-aliased text on solid backgrounds
//! - Graceful fallback to bitmap font if atlas is missing or invalid
//! - Validates magic, header fields, and glyph bounds; never panics on corrupt data

#![allow(dead_code)]

use crate::framebuffer::Framebuffer;

/// Pre-rasterized MTF font blobs embedded at build time.
/// UI chrome fonts from Inter; terminal mono fonts from Fira Code.
/// Generated by sunlight-tui/build.rs using fontdue — no runtime TTF parser.
static FONT_REGULAR_15: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/login_regular_15.mtf"));
static FONT_TITLE_24: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/login_title_24.mtf"));
static FONT_MONO_REGULAR: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/tty_mono_regular_14.mtf"));
static FONT_MONO_BOLD: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tty_mono_bold_14.mtf"));

const MTF_MAGIC: &[u8; 4] = b"MTF1";
const HEADER_SIZE: usize = 8;
const GLYPH_COUNT: usize = 95;
const OFFSET_TABLE_SIZE: usize = GLYPH_COUNT * 4;
const GLYPH_DATA_START: usize = HEADER_SIZE + OFFSET_TABLE_SIZE;
const GLYPH_FIRST: u8 = 0x20;
const GLYPH_LAST: u8 = 0x7E;

const MAX_ATLAS_BYTES: usize = 256 * 1024;
const MAX_GLYPH_DIM: u8 = 64;
const MAX_LINE_HEIGHT: u8 = 64;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FontSize {
    /// Inter 15px — TTY UI chrome: header labels, tabs, footer hints
    Regular,
    /// Inter 24px — TTY UI title / large headings
    Title,
    /// Fira Code Regular 14px — shell/terminal grid cells
    MonoRegular,
    /// Fira Code SemiBold 14px — bold terminal text
    MonoBold,
}

struct AtlasHeader {
    line_height: u8,
    ascent: u8,
}

struct GlyphMetrics {
    advance: u8,
    left: i8,
    top: i8,
    width: u8,
    height: u8,
    pixel_offset: usize,
}

fn validate_header(data: &[u8]) -> Option<AtlasHeader> {
    if data.len() < GLYPH_DATA_START || data.len() > MAX_ATLAS_BYTES {
        return None;
    }
    if &data[0..4] != MTF_MAGIC {
        return None;
    }
    let line_height = data[4];
    let ascent = data[5];
    let glyph_count = data[6];

    if line_height == 0
        || line_height > MAX_LINE_HEIGHT
        || ascent > line_height
        || glyph_count as usize != GLYPH_COUNT
    {
        return None;
    }
    Some(AtlasHeader {
        line_height,
        ascent,
    })
}

#[inline]
fn read_u32(data: &[u8], pos: usize) -> u32 {
    if pos + 4 > data.len() {
        return 0;
    }
    u32::from_le_bytes([data[pos], data[pos + 1], data[pos + 2], data[pos + 3]])
}

fn lookup_glyph(data: &[u8], ch: u8) -> Option<GlyphMetrics> {
    let ch = if ch >= GLYPH_FIRST && ch <= GLYPH_LAST {
        ch
    } else {
        b'?'
    };
    let idx = (ch - GLYPH_FIRST) as usize;
    let offset_pos = HEADER_SIZE + idx * 4;
    if offset_pos + 4 > data.len() {
        return None;
    }
    let glyph_start = read_u32(data, offset_pos) as usize;
    if glyph_start < GLYPH_DATA_START || glyph_start + 5 > data.len() {
        return None;
    }
    let advance = data[glyph_start];
    let left = data[glyph_start + 1] as i8;
    let top = data[glyph_start + 2] as i8;
    let width = data[glyph_start + 3];
    let height = data[glyph_start + 4];
    if width > MAX_GLYPH_DIM || height > MAX_GLYPH_DIM {
        return None;
    }
    let pixel_offset = glyph_start + 5;
    let pixel_end = pixel_offset + (width as usize) * (height as usize);
    if pixel_end > data.len() {
        return None;
    }
    Some(GlyphMetrics {
        advance,
        left,
        top,
        width,
        height,
        pixel_offset,
    })
}

#[inline(always)]
fn alpha_blend(dst: u32, src: u32, alpha: u8) -> u32 {
    if alpha == 0 {
        return dst;
    }
    if alpha == 255 {
        return src;
    }
    let a = alpha as u32;
    let ia = 255 - a;
    let r = ((src >> 16 & 0xFF) * a + (dst >> 16 & 0xFF) * ia) / 255;
    let g = ((src >> 8 & 0xFF) * a + (dst >> 8 & 0xFF) * ia) / 255;
    let b = ((src & 0xFF) * a + (dst & 0xFF) * ia) / 255;
    (r << 16) | (g << 8) | b
}

fn draw_glyph_at(
    fb: &mut Framebuffer,
    pen_x: i32,
    baseline_y: i32,
    m: &GlyphMetrics,
    data: &[u8],
    color: u32,
) {
    let bx = pen_x + m.left as i32;
    let by = baseline_y - m.top as i32;
    let fb_w = fb.width() as i32;
    let fb_h = fb.height() as i32;
    for row in 0..m.height as i32 {
        let py = by + row;
        if py < 0 || py >= fb_h {
            continue;
        }
        for col in 0..m.width as i32 {
            let px = bx + col;
            if px < 0 || px >= fb_w {
                continue;
            }
            let alpha_idx = m.pixel_offset + row as usize * m.width as usize + col as usize;
            if alpha_idx >= data.len() {
                continue;
            }
            let alpha = data[alpha_idx];
            if alpha == 0 {
                continue;
            }
            let dst = fb.get_pixel(px as u32, py as u32);
            fb.put_pixel(px as u32, py as u32, alpha_blend(dst, color, alpha));
        }
    }
}

#[inline]
fn blob(size: FontSize) -> &'static [u8] {
    match size {
        FontSize::Regular => FONT_REGULAR_15,
        FontSize::Title => FONT_TITLE_24,
        FontSize::MonoRegular => FONT_MONO_REGULAR,
        FontSize::MonoBold => FONT_MONO_BOLD,
    }
}

#[inline]
fn fallback_scale(size: FontSize) -> u32 {
    match size {
        FontSize::Regular | FontSize::MonoRegular | FontSize::MonoBold => 1,
        FontSize::Title => 2,
    }
}

pub fn draw_text(
    fb: &mut Framebuffer,
    text: &str,
    x: u32,
    y: u32,
    color: u32,
    size: FontSize,
) -> u32 {
    let data = blob(size);
    let header = match validate_header(data) {
        Some(h) => h,
        None => {
            crate::font::draw_str(fb, x, y, text, color, fallback_scale(size));
            return x + crate::font::text_width(text, fallback_scale(size));
        }
    };
    let mut pen_x = x as i32;
    let baseline_y = y as i32 + header.ascent as i32;
    for &byte in text.as_bytes() {
        match byte {
            b'\n' | b'\r' => {}
            _ => match lookup_glyph(data, byte) {
                Some(m) => {
                    draw_glyph_at(fb, pen_x, baseline_y, &m, data, color);
                    pen_x += m.advance as i32;
                }
                None => {
                    pen_x += header.line_height as i32 / 2;
                }
            },
        }
    }
    pen_x.max(0) as u32
}

pub fn measure_text(text: &str, size: FontSize) -> u32 {
    let data = blob(size);
    if validate_header(data).is_none() {
        return crate::font::text_width(text, fallback_scale(size));
    }
    let mut width = 0u32;
    for &byte in text.as_bytes() {
        match byte {
            b'\n' | b'\r' => {}
            _ => {
                if let Some(m) = lookup_glyph(data, byte) {
                    width += m.advance as u32;
                } else {
                    width += 8;
                }
            }
        }
    }
    width
}

pub fn line_height(size: FontSize) -> u32 {
    let data = blob(size);
    if let Some(h) = validate_header(data) {
        h.line_height as u32
    } else {
        match size {
            FontSize::Regular => 18,
            FontSize::Title => 32,
            FontSize::MonoRegular | FontSize::MonoBold => 18,
        }
    }
}

pub fn atlas_is_valid(size: FontSize) -> bool {
    validate_header(blob(size)).is_some()
}

/// Returns `(cell_w, cell_h)` for terminal grid sizing from a mono font atlas.
///
/// `cell_w` is the advance width of the space character (all monospace chars share it).
/// `cell_h` is the line height from the atlas header.
/// Falls back to `(8, 18)` if the atlas is missing or invalid.
pub fn cell_metrics(size: FontSize) -> (u32, u32) {
    let data = blob(size);
    match validate_header(data) {
        Some(h) => {
            let cell_w = lookup_glyph(data, b' ')
                .map(|m| m.advance as u32)
                .filter(|&w| w >= 4 && w <= 32)
                .unwrap_or(8);
            (cell_w, h.line_height as u32)
        }
        None => (8, 18),
    }
}

/// Draw a single character into a terminal cell using an atlas font.
///
/// `cell_x, cell_y` is the top-left of the cell. The cell background must
/// already be filled before calling this. Alpha-blends the glyph onto whatever
/// is on screen, so it works correctly on any background color.
///
/// Falls back to the bitmap font if the atlas is missing or invalid.
pub fn draw_mono_char(
    fb: &mut Framebuffer,
    cell_x: u32,
    cell_y: u32,
    cell_h: u32,
    ch: u8,
    fg: u32,
    size: FontSize,
) {
    let data = blob(size);
    let header = match validate_header(data) {
        Some(h) => h,
        None => {
            crate::font::draw_char(fb, cell_x, cell_y, ch, fg, 1);
            return;
        }
    };
    let m = match lookup_glyph(data, ch) {
        Some(m) => m,
        None => return,
    };
    let pen_x = cell_x as i32;
    let baseline_y = cell_y as i32 + header.ascent as i32;
    let bx = pen_x + m.left as i32;
    let by = baseline_y - m.top as i32;
    let fb_w = fb.width() as i32;
    let fb_h = fb.height() as i32;
    let clip_bottom = (cell_y + cell_h) as i32;

    for row in 0..m.height as i32 {
        let py = by + row;
        if py < 0 || py >= fb_h || py >= clip_bottom {
            continue;
        }
        for col in 0..m.width as i32 {
            let px = bx + col;
            if px < 0 || px >= fb_w {
                continue;
            }
            let alpha_idx = m.pixel_offset + row as usize * m.width as usize + col as usize;
            if alpha_idx >= data.len() {
                continue;
            }
            let alpha = data[alpha_idx];
            if alpha == 0 {
                continue;
            }
            let dst = fb.get_pixel(px as u32, py as u32);
            fb.put_pixel(px as u32, py as u32, alpha_blend(dst, fg, alpha));
        }
    }
}
