[package]
name = "hello-linux"
version = "0.2.3989-alpha.1"























































































































































































































































































































































































































































edition = "2021"

[workspace]

[[bin]]
name = "hello-linux"
path = "src/main.rs"
