; VGALAB.COM - Chronos Prompt 5A direct Mode 13h framebuffer demonstration
; NASM, 8086 real mode. Every visible shape is generated by guest writes to
; A000:0000; BIOS is used only to select modes and wait for a key.

bits 16
org 0x100

start:
    mov ax, 0x0013
    int 0x10

    mov ax, 0xa000
    mov es, ax
    cld

    ; Authoritative full-screen guest fill (the cooperative interpreter keeps
    ; REP resumable across execution slices).
    xor di, di
    mov al, 1
    mov cx, 64000
    rep stosb

    ; Sixteen classic-color vertical bands across the top 32 rows.
    xor bx, bx
    mov si, band_colors
    mov dx, 16
.band:
    lodsb
    mov di, bx
    mov bp, 32
.band_row:
    mov cx, 20
    rep stosb
    add di, 300
    dec bp
    jnz .band_row
    add bx, 20
    dec dx
    jnz .band

    ; A deterministic indexed ramp, 320 individual pixels on each of 16 rows.
    mov di, 10240                 ; y=32, x=0
    mov bp, 16
.ramp_row:
    mov cx, 320
    mov al, 16
.ramp_pixel:
    stosb
    inc al
    loop .ramp_pixel
    dec bp
    jnz .ramp_row

    ; 96x64 cyan checkerboard at (16,64), using 8x8 tiles.
    mov di, 20496
    mov dh, 8
    mov bl, 3
.checker_block:
    mov dl, 8
.checker_row:
    push di
    mov bp, 12
    mov al, bl
.checker_tile:
    mov cx, 8
    rep stosb
    xor al, 8
    dec bp
    jnz .checker_tile
    pop di
    add di, 320
    dec dl
    jnz .checker_row
    xor bl, 8
    dec dh
    jnz .checker_block

    ; Yellow frame around the lower composition.
    mov al, 14
    mov di, 17928                 ; (8,56)
    mov cx, 304
    rep stosb
    mov di, 61128                 ; (8,191)
    mov cx, 304
    rep stosb
    mov di, 18248                 ; (8,57)
    mov cx, 134
.frame_sides:
    mov [es:di], al
    mov [es:di+303], al
    add di, 320
    loop .frame_sides

    ; Two diagonals, deliberately plotted as calculated individual offsets.
    mov al, 12
    mov di, 20496                 ; (16,64)
    mov cx, 120
.diagonal_down:
    mov [es:di], al
    add di, 321
    loop .diagonal_down

    mov al, 10
    mov di, 20783                 ; (303,64)
    mov cx, 120
.diagonal_up:
    mov [es:di], al
    add di, 319
    loop .diagonal_up

    ; Centered orange/yellow square sun motif with a bright core.
    mov al, 6
    mov di, 27020                 ; (140,84)
    mov bp, 40
.sun_outer_row:
    mov cx, 40
    rep stosb
    add di, 280
    dec bp
    jnz .sun_outer_row

    mov al, 14
    mov di, 28946                 ; (146,90)
    mov bp, 28
.sun_inner_row:
    mov cx, 28
    rep stosb
    add di, 292
    dec bp
    jnz .sun_inner_row

    mov al, 15
    mov di, 31512                 ; (152,98)
    mov bp, 12
.sun_core_row:
    mov cx, 16
    rep stosb
    add di, 304
    dec bp
    jnz .sun_core_row

.wait_escape:
    mov ah, 0x00
    int 0x16
    cmp al, 0x1b
    jne .wait_escape

    mov ax, 0x0003
    int 0x10
    mov ax, 0x4c00
    int 0x21

band_colors:
    db 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
