[package]
name = "sunlight-tty-server"
version = "0.2.2205-alpha.1"













































































































































































































































































































































































































edition = "2021"

[[bin]]
name = "sunlight-tty-server"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-fs  = { path = "../../sunlight-fs" }
sunlight-tty = { path = "../../sunlight-tty" }
sunlight-tui = { path = "../../sunlight-tui" }
sunlight-libc = { path = "../../sunlight-libc" }
