[package]
name = "sunlight-usb-mouse"
version = "0.2.3839-alpha.1"




























































































edition = "2021"

[features]
usb_mouse_debug = []

[dependencies]
sunlight-ipc = { path = "../../ipc" }

[[bin]]
name = "sunlight-usb-mouse"
path = "src/main.rs"
