[package]
name = "sunlight-sessionctl"
version = "0.2.3429-alpha.1"










edition = "2021"

[dependencies]
heapless = "0.8"
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc", features = ["global-alloc"] }

[[bin]]
name = "sunlight-sessionctl"
path = "src/main.rs"
