[package]
name = "certificatectl"
version = "0.2.2199-alpha.1"



























































































































































































































































































































































































edition = "2021"
description = "CLI client for sunlight-tls (certificate management)"

[[bin]]
name = "certificatectl"
path = "src/main.rs"

[features]
default = ["host"]
host = []
sunlightos = [
    "dep:sunlight-ipc",
    "dep:sunlight-libc",
    "dep:heapless",
]

[dependencies]
sunlight-ipc  = { path = "../ipc", optional = true }
sunlight-libc = { path = "../sunlight-libc", optional = true }
heapless      = { version = "0.8", optional = true }
