[package]
name = "sunlight-sessiond"
version = "0.2.4073-alpha.1"




























































edition = "2021"

[dependencies]
heapless = "0.8"
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }

[[bin]]
name = "sunlight-sessiond"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[features]
default = []
# Optional: enable ISO inject-phase seeding of a test Startup App.
session-configuration-inject = []
