[package]
name = "sunlight-vortex-shell"
version = "0.2.974"
























































































































edition = "2021"

[build-dependencies]
fontdue = "0.7"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-telemetry = { path = "../../sunlight-telemetry" }
sunlight-ui = { path = "../../sunlight-ui", features = ["app"] }
sun-font = { path = "../../sun-font" }
sunlight-wallpaper = { path = "../../sunlight-wallpaper" }
sunlight-locale = { path = "../../sunlight-locale" }
sunlight-tz = { path = "../../sunlight-tz" }

[[bin]]
name = "sunlight-vortex-shell"
path = "src/main.rs"
