[package]
name = "sunlight-block"
version = "0.2.1764"
























































































































































































































































































































































edition = "2021"

[lib]
