[package]
name = "sunlight-block"
version = "0.2.1556"






























































































































































































































































































































edition = "2021"

[lib]
