[package]
name = "sunlight-block"
version = "0.2.1753"



















































































































































































































































































































































edition = "2021"

[lib]
