[package]
name = "sunlight-virtio"
version = "0.2.1784"





























































































































































































































































































































































edition = "2021"

[lib]
