[package]
name = "sunlight-virtio"
version = "0.2.1765"

























































































































































































































































































































































edition = "2021"

[lib]
