[package]
name = "sunlight-compat-linux"
version = "0.2.2402-alpha.1"



















































































































































































































































































































































































































authors = ["SunlightOS Team"]
edition = "2021"

[dependencies]
heapless = "0.8"
