[package]
name = "sunlight-compat-linux"
version = "0.2.864"

























































































































































































































authors = ["SunlightOS Team"]
edition = "2021"

[dependencies]
heapless = "0.8"
