[package]
name = "sunlight-emoji-picker"
version = "0.2.1719"










































edition = "2021"

[[bin]]
name = "sunlight-emoji-picker"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
