[package]
name = "sunlight-deviced"
version = "0.2.2109-alpha.1"





















































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[[bin]]
name = "deviced"
path = "src/main.rs"

[[bin]]
name = "devicectl"
path = "src/bin/devicectl.rs"

[[bin]]
name = "sunlight-hwinfo"
path = "src/bin/sunlight-hwinfo.rs"
