[package]
name    = "sunshell"
version = "0.2.3592-alpha.1"























































































































































































































































































































































































































































































edition = "2021"

[lib]
name = "sunshell"
path = "src/lib.rs"

[[bin]]
name = "sshl"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc", optional = true }
sunlight-libc = { path = "../sunlight-libc", optional = true }
sunlight-uac = { path = "../services/sunlight-uac", optional = true }
sunlight-tz = { path = "../sunlight-tz" }
sunlight-locale = { path = "../sunlight-locale" }
libm = "0.2"

[features]
default = ["sunlight"]
std = []
sunlight = ["sunlight-ipc", "sunlight-libc", "sunlight-uac"]
