[package]
name    = "sunshell"
version = "0.1.472"




















































































































edition = "2021"

[[bin]]
name = "sshl"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc", optional = true }
sunlight-libc = { path = "../sunlight-libc", optional = true }
sunlight-tz = { path = "../sunlight-tz" }
libm = "0.2"

[features]
default = ["sunlight"]
std = []
sunlight = ["sunlight-ipc", "sunlight-libc"]
