[package]
name = "sunlight-utils"
version = "0.2.1398"









































































































































































































































































































edition = "2021"

[[bin]]
name = "sunlight-utils"
path = "src/main.rs"

[dependencies]
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ipc = { path = "../ipc" }
memchr = { version = "2", default-features = false }
