[package]
name = "sunlight-utils"
version = "0.2.3396-alpha.1"

















edition = "2021"

[lib]
name = "sunlight_utils"
path = "src/lib.rs"




















































































































































































































































































































































































































































[[bin]]
name = "sunlight-utils"
path = "src/main.rs"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"

[[bin]]
name = "cat"
path = "src/bin/cat.rs"

[[bin]]
name = "pwd"
path = "src/bin/pwd.rs"

[[bin]]
name = "true"
path = "src/bin/true.rs"

[[bin]]
name = "false"
path = "src/bin/false.rs"

[[bin]]
name = "basename"
path = "src/bin/basename.rs"

[[bin]]
name = "dirname"
path = "src/bin/dirname.rs"

[[bin]]
name = "head"
path = "src/bin/head.rs"

[[bin]]
name = "cmp"
path = "src/bin/cmp.rs"

[[bin]]
name = "cksum"
path = "src/bin/cksum.rs"

[[bin]]
name = "wc"
path = "src/bin/wc.rs"

[[bin]]
name = "cut"
path = "src/bin/cut.rs"

[[bin]]
name = "fold"
path = "src/bin/fold.rs"

[[bin]]
name = "expand"
path = "src/bin/expand.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[[bin]]
name = "sort"
path = "src/bin/sort.rs"

[[bin]]
name = "uniq"
path = "src/bin/uniq.rs"

[[bin]]
name = "comm"
path = "src/bin/comm.rs"

[[bin]]
name = "tee"
path = "src/bin/tee.rs"

[[bin]]
name = "nl"
path = "src/bin/nl.rs"

[[bin]]
name = "od"
path = "src/bin/od.rs"

[[bin]]
name = "split"
path = "src/bin/split.rs"

[[bin]]
name = "find"
path = "src/bin/find.rs"

[[bin]]
name = "xargs"
path = "src/bin/xargs.rs"

[dependencies]
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ipc = { path = "../ipc" }
memchr = { version = "2", default-features = false }
