[package]
name = "sunlight-utils"
version = "0.2.2671-alpha.1"

edition = "2021"

[lib]
name = "sunlight_utils"
path = "src/lib.rs"




















































































































































































































































































































































































































































[[bin]]
name = "sunlight-utils"
path = "src/main.rs"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"

[dependencies]
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ipc = { path = "../ipc" }
memchr = { version = "2", default-features = false }
