[package]
name = "sun-imgc"
version = "0.2.2763-alpha.1"
























































































































































































































edition = "2021"
description = "Minimal color image conversion CLI for SunlightOS"
license = "MIT"

[dependencies]
sun-img = { path = "../sun-img" }
