[package]
name = "sunlight-timed"
version = "0.2.704"




























































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }

[[bin]]
name = "timed"
path = "src/main.rs"
