[package]
name = "sunlight-timed"
version = "0.2.3747-alpha.1"
































































edition = "2021"

[lib]
name = "sunlight_timed"
path = "src/lib.rs"

[[bin]]
name = "timed"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-tz = { path = "../../sunlight-tz" }
