[package]
name = "sunlight-control-panel"
version = "0.2.1757"








































































































































































































edition = "2021"
build = "build.rs"

[[bin]]
name = "control-panel"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-ui = { path = "../../sunlight-ui", features = ["app"] }
sunlight-wallpaper = { path = "../../sunlight-wallpaper" }
sun-font = { path = "../../sun-font" }

[build-dependencies]
fontdue = "0.7"
image = { version = "0.25.9", default-features = false, features = ["png"] }
