[package]
name = "helios-note"
version = "0.2.3247-alpha.1"



































































































































































































































































































































































































edition = "2021"

[dependencies]
libc = "0.2"
tui = { version = "0.19", default-features = false, features = ["crossterm"] }
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }
crossterm = "0.25"
