//! Build-time codegen: parses docs/Timezones.csv once at build time and
//! emits a static `ZONES: &[TzEntry]` array into OUT_DIR. This avoids
//! parsing a 559-row CSV at runtime in a no_std/no_alloc context (which
//! was capped at MAX_ZONES=256 and silently dropped later rows).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let csv_path = Path::new(&manifest_dir).join("../docs/Timezones.csv");
    println!("cargo:rerun-if-changed={}", csv_path.display());

    let csv = fs::read_to_string(&csv_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", csv_path.display()));

    let mut out = String::new();
    out.push_str("// @generated by sunlight-tz/build.rs from docs/Timezones.csv. Do not edit.\n");
    out.push_str("pub static ZONES: &[TzEntry] = &[\n");

    for (lineno, line) in csv.lines().enumerate() {
        if lineno == 0 {
            continue; // header
        }
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let fields: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
        if fields.len() != 4 {
            continue; // malformed row, skip
        }

        let id = fields[0];
        let offset_str = fields[1];
        let dst_str = fields[2];
        let display_name = fields[3];

        if id.is_empty() || display_name.is_empty() {
            continue;
        }

        let (h, m) = match parse_offset_hm(offset_str) {
            Some(v) => v,
            None => continue,
        };

        let dst_mins: i32 = dst_str.parse().unwrap_or(0).max(0);
        let dst_mins: u8 = if dst_mins > 255 { 255 } else { dst_mins as u8 };

        let (dst_start, dst_end) = if dst_mins > 0 { (3u8, 9u8) } else { (0u8, 0u8) };

        let (region, city) = split_region_city(id);

        out.push_str(&format!(
            "    TzEntry {{ id: {id:?}, region: {region:?}, city: {city:?}, display_name: {display_name:?}, utc_offset_hours: {h}, utc_offset_minutes: {m}, dst_offset_minutes: {dst_mins}, dst_start_month: {dst_start}, dst_end_month: {dst_end} }},\n"
        ));
    }

    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("zones_data.rs"), out).unwrap();
}

/// Parse " -12 : 00 " style into (hours i8, minutes u8). Returns None on error.
fn parse_offset_hm(s: &str) -> Option<(i8, u8)> {
    let norm: String = s.chars().filter(|c| !c.is_whitespace()).collect();
    let mut parts = norm.split(':');
    let h: i32 = parts.next()?.parse().ok()?;
    let m: i32 = match parts.next() {
        Some(p) if !p.is_empty() => p.parse().ok()?,
        _ => 0,
    };
    if !(0..=59).contains(&m) {
        return None;
    }
    Some((h as i8, m as u8))
}

/// Split id into (region, city). For "Asia/Tehran" -> ("Asia","Tehran")
/// For "UTC" or no-slash -> (id, id)
fn split_region_city(id: &str) -> (&str, &str) {
    match id.rfind('/') {
        Some(pos) => (&id[..pos], &id[pos + 1..]),
        None => (id, id),
    }
}
