[package]
name = "sunlight-powerd"
version = "0.1.510"







































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[[bin]]
name = "powerd"
path = "src/main.rs"

[[bin]]
name = "powerctl"
path = "src/bin/powerctl.rs"
