[package]
name = "secret_store_test"
version = "0.2.3504-alpha.1"





















































































































edition = "2021"

[dependencies]
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-ipc = { path = "../../ipc" }
