[Icon Theme]
Name=SunlightOS-Night-Icons
Inherits=hicolor
Comment=Breeze icon adpated for SunlightOS


Directories=actions/16,actions/32,actions/symbolic,actions/scalable,animations/16,animations/22,apps/16,apps/48,apps/64,apps/scalable,apps/symbolic,categories/22,categories/24,categories/32,devices/16,devices/64,devices/symbolic,emblems/16,emblems/22,emblems/24,emblems/symbolic,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/64,mimetypes/symbolic,places/16,places/22,places/32,places/64,places/96,places/symbolic,preferences/22,preferences/32,status/48,status/64,status/symbolic
ScaledDirectories=actions/16@2x,animations/16@2x,apps/16@2x,categories/24@2x,categories/24@3x,places/16@2x

########## Actions

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/16@2x]
Size=16
Scale=2
Context=Actions
Type=Fixed

[actions/32]
Size=32
Context=Actions
Type=Fixed
MinSize=32
MaxSize=256

[actions/symbolic]
Size=16
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/scalable]
Size=16
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

########## Animations

[animations/16]
Size=16
Context=Animations
Type=Fixed

[animations/16@2x]
Size=16
Scale=2
Context=Animations
Type=Fixed

[animations/22]
Size=22
Context=Animations
Type=Scalable
MinSize=22
MaxSize=256

########## Apps

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/16@2x]
Size=16
Scale=2
Context=Applications
Type=Fixed

[apps/48]
Size=48
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

[apps/64]
Size=64
Context=Applications
Type=Scalable
MinSize=64
MaxSize=256

[apps/scalable]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/symbolic]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

########## Categories

[categories/22]
Size=22
Context=Categories
Type=Scalable
MinSize=22
MaxSize=256

[categories/24]
Size=24
Context=Categories
Type=Scalable
MinSize=24
MaxSize=256

[categories/24@2x]
Size=24
Scale=2
Context=Categories
Type=Fixed
MinSize=24

[categories/24@3x]
Size=24
Scale=3
Context=Categories
Type=Fixed
MinSize=24

[categories/32]
Size=32
Context=Categories
Type=Scalable
MinSize=32
MaxSize=256

########## Devices

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/64]
Size=64
Context=Devices
Type=Scalable
MinSize=24
MaxSize=256

[devices/symbolic]
Size=16
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

########## Emblems

[emblems/16]
Size=16
Context=Emblems
Type=Fixed

[emblems/22]
Size=22
Context=Emblems
Type=Fixed

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[emblems/symbolic]
Size=16
Context=Emblems
MinSize=16
MaxSize=96
Type=Scalable

########## Mimetypes

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed
MinSize=16

[mimetypes/22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

[mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

[mimetypes/64]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=64
MaxSize=256

[mimetypes/symbolic]
Size=16
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

########## Places

[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

[places/16@2x]
Size=16
Scale=2
Context=Places
Type=Fixed
MinSize=16

[places/22]
Size=22
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/96]
Size=96
Context=Places
Type=Scalable
MinSize=96
MaxSize=256

[places/symbolic]
Size=16
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

########## Preferences

[preferences/32]
Size=32
Context=Preferences
Type=Scalable
MinSize=32
MaxSize=256

[preferences/22]
Size=22
Context=Preferences
Type=Fixed

########## Status

[status/48]
Size=48
Context=Status
Type=Fixed

[status/64]
Size=64
Context=Status
Type=Scalable
MinSize=22
MaxSize=256

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

########## EOF
