//! Standalone POSIX `printf` utility.  This is a utility format parser, not a
//! wrapper around libc/Rust formatting.  Floating conversions are intentionally
//! rejected: the current maintained runtime has no floating formatter.

use sunlight_libc::{Errno, STDERR, STDOUT};

const MAX_VALUE: usize = 1024;
const PAD_CHUNK: [u8; 32] = [b' '; 32];

pub trait Io { fn write_stdout(&mut self,b:&[u8])->Result<(),Errno>; fn write_stderr(&mut self,b:&[u8])->Result<(),Errno>; }
pub fn user_args<'a>(argv:&'a[&'a[u8]])->&'a[&'a[u8]]{argv.get(1..).unwrap_or(&[])}

#[derive(Clone,Copy)]struct Spec{flags:u8,width:usize,precision:Option<usize>,conv:u8,consumes:bool}
const LEFT:u8=1;const PLUS:u8=2;const SPACE:u8=4;const ALT:u8=8;const ZERO:u8=16;

pub fn run(args:&[&[u8]],io:&mut impl Io)->i32{if args.is_empty(){diag(io,b"printf: missing format operand\n");return 2}let format=args[0];let values=&args[1..];let mut arg=0;let mut status=0;let mut passes=0;loop{passes+=1;if passes>values.len()+1{diag(io,b"printf: format reuse limit\n");return 1}let mut consumed=0;let stop=match render(format,values,&mut arg,&mut consumed,io,&mut status){Ok(stop)=>stop,Err(())=>return 1};if stop||arg>=values.len()||consumed==0{break}}status}

fn render(format:&[u8],values:&[&[u8]],arg:&mut usize,consumed:&mut usize,io:&mut impl Io,status:&mut i32)->Result<bool,()>{let mut i=0;while i<format.len(){if format[i]!=b'%'&&format[i]!=b'\\'{write(io,&format[i..i+1])?;i+=1;continue}if format[i]==b'\\'{let (b,n)=decode_format(format,i)?;write(io,&[b])?;i=n;continue}if i+1<format.len()&&format[i+1]==b'%'{write(io,b"%")?;i+=2;continue}let (spec,n)=parse_spec(format,i)?;i=n;if !spec.consumes{if spec.conv==b'%' {write(io,b"%")?;}continue}*consumed+=1;let value=if *arg<values.len(){let v=values[*arg];*arg+=1;v}else{&[]};if spec.conv==b'b'{let mut decoded=[0u8;MAX_VALUE];let (len,stop)=decode_b(value,&mut decoded)?;if stop{format_string(&decoded[..len],&spec,io)?;return Ok(true)}format_string(&decoded[..len],&spec,io)?;continue}match spec.conv{b's'=>format_string(value,&spec,io)?,b'c'=>{let one=value.first().copied().unwrap_or(0);format_string(core::slice::from_ref(&one),&spec,io)?},b'd'|b'i'=>{let v=parse_signed(value).unwrap_or_else(||{*status=1;diag(io,b"printf: invalid signed integer\n");0});let mut buf=[0u8;MAX_VALUE];let len=render_signed(v,&spec,&mut buf);format_string(&buf[..len],&Spec{flags:spec.flags&!(LEFT|ZERO),width:spec.width,precision:None,conv:b's',consumes:false},io)?},b'u'=>{let v=parse_unsigned(value).unwrap_or_else(||{*status=1;diag(io,b"printf: invalid unsigned integer\n");0});let mut buf=[0u8;MAX_VALUE];let len=render_unsigned(v,10,false,&spec,&mut buf);format_string(&buf[..len],&Spec{flags:spec.flags&!(LEFT|ZERO),width:spec.width,precision:None,conv:b's',consumes:false},io)?},b'o'=>{let v=parse_unsigned(value).unwrap_or_else(||{*status=1;diag(io,b"printf: invalid octal integer\n");0});let mut buf=[0u8;MAX_VALUE];let len=render_unsigned(v,8,false,&spec,&mut buf);format_string(&buf[..len],&Spec{flags:spec.flags&!(LEFT|ZERO),width:spec.width,precision:None,conv:b's',consumes:false},io)?},b'x'|b'X'=>{let v=parse_unsigned(value).unwrap_or_else(||{*status=1;diag(io,b"printf: invalid hexadecimal integer\n");0});let mut buf=[0u8;MAX_VALUE];let len=render_unsigned(v,16,spec.conv==b'X',&spec,&mut buf);format_string(&buf[..len],&Spec{flags:spec.flags&!(LEFT|ZERO),width:spec.width,precision:None,conv:b's',consumes:false},io)?},_=>{diag(io,b"printf: unsupported conversion\n");*status=1;return Err(())}}}Ok(false)}

fn parse_spec(f:&[u8],at:usize)->Result<(Spec,usize),()>{let mut i=at+1;let mut flags=0;while i<f.len(){flags|=match f[i]{b'-'=>LEFT,b'+'=>PLUS,b' '=>SPACE,b'#'=>ALT,b'0'=>ZERO,_=>break};if !matches!(f[i],b'-'|b'+'|b' '|b'#'|b'0'){break}i+=1}let start=i;while i<f.len()&&f[i].is_ascii_digit(){i+=1}let width=parse_dec(&f[start..i])?;let precision=if i<f.len()&&f[i]==b'.'{i+=1;let s=i;while i<f.len()&&f[i].is_ascii_digit(){i+=1}Some(parse_dec(&f[s..i])?)}else{None};if i>=f.len(){return Err(())}let conv=f[i];if !matches!(conv,b'b'|b'c'|b'd'|b'i'|b'o'|b's'|b'u'|b'x'|b'X'|b'%'){return Err(())}Ok((Spec{flags,width,precision,conv,consumes:conv!=b'%'},i+1))}
fn parse_dec(b:&[u8])->Result<usize,()>{let mut n=0;for &c in b{let d=(c-b'0')as usize;if n>(usize::MAX-d)/10{return Err(())}n=n*10+d}Ok(n)}
fn decode_format(f:&[u8],at:usize)->Result<(u8,usize),()>{if at+1>=f.len(){return Err(())}match f[at+1]{b'a'=>Ok((7,at+2)),b'b'=>Ok((8,at+2)),b'f'=>Ok((12,at+2)),b'n'=>Ok((10,at+2)),b'r'=>Ok((13,at+2)),b't'=>Ok((9,at+2)),b'v'=>Ok((11,at+2)),b'\\'=>Ok((b'\\',at+2)),b'0'..=b'7'=>{let mut n=0u16;let mut i=at+1;let mut c=0;while i<f.len()&&c<3&&(b'0'..=b'7').contains(&f[i]){n=n*8+(f[i]-b'0')as u16;i+=1;c+=1}Ok((n as u8,i))},_=>Err(())}}
fn decode_b(src:&[u8],out:&mut[u8;MAX_VALUE])->Result<(usize,bool),()>{let mut i=0;let mut n=0;while i<src.len(){let b=if src[i]!=b'\\'{let b=src[i];i+=1;b}else{let (b,next)=if i+1>=src.len(){return Err(())}else{match src[i+1]{b'c'=>return Ok((n,true)),b'0'..=b'7'=>{let mut v=0u16;let mut j=i+1;let mut k=0;while j<src.len()&&k<3&&(b'0'..=b'7').contains(&src[j]){v=v*8+(src[j]-b'0')as u16;j+=1;k+=1}(v as u8,j)},b'a'=> (7,i+2),b'b'=>(8,i+2),b'f'=>(12,i+2),b'n'=>(10,i+2),b'r'=>(13,i+2),b't'=>(9,i+2),b'v'=>(11,i+2),b'\\'=>(b'\\',i+2),_=>return Err(())}};i=next;b};if n==out.len(){return Err(())}out[n]=b;n+=1}Ok((n,false))}

fn parse_signed(b:&[u8])->Option<i64>{if b.is_empty(){return Some(0)}if b.len()>=2&&(b[0]==b'\''||b[0]==b'"'){return Some(b[1]as i64)}let mut i=0;let neg=if b[0]==b'-'{i+=1;true}else{if b[0]==b'+'{i+=1};false};let base=if i+2<=b.len()&&b[i]==b'0'&&(b[i+1]==b'x'||b[i+1]==b'X'){i+=2;16}else if i<b.len()&&b[i]==b'0'{8}else{10};let mut n=0i64;let mut any=false;while i<b.len(){let d=digit(b[i])?;if d>=base{return None}any=true;n=n.checked_mul(base)?.checked_add(d)?;i+=1}if !any{return None}if neg{n.checked_neg()}else{Some(n)}}
fn parse_unsigned(b:&[u8])->Option<u64>{if b.is_empty(){return Some(0)}if b.len()>=2&&(b[0]==b'\''||b[0]==b'"'){return Some(b[1]as u64)}let mut i=0;if b[0]==b'+'{i+=1}else if b[0]==b'-'{return None}let base:i64=if i+2<=b.len()&&b[i]==b'0'&&(b[i+1]==b'x'||b[i+1]==b'X'){i+=2;16}else if i<b.len()&&b[i]==b'0'{8}else{10};let mut n=0u64;let mut any=false;while i<b.len(){let d=digit(b[i])?;if d>=base{return None}any=true;n=n.checked_mul(base as u64)?.checked_add(d as u64)?;i+=1}any.then_some(n)}
fn digit(b:u8)->Option<i64>{match b{b'0'..=b'9'=>Some((b-b'0')as i64),b'a'..=b'f'=>Some((b-b'a'+10)as i64),b'A'..=b'F'=>Some((b-b'A'+10)as i64),_=>None}}

fn render_signed(v:i64,s:&Spec,out:&mut[u8;MAX_VALUE])->usize{let mut mag=if v<0{(!v as u64).wrapping_add(1)}else{v as u64};let mut digits=[0u8;MAX_VALUE];let mut n=0;loop{digits[n]=b'0'+(mag%10)as u8;n+=1;mag/=10;if mag==0{break}}let min=s.precision.unwrap_or(0);while n<min{digits[n]=b'0';n+=1}let mut p=0;if v<0{out[p]=b'-';p+=1}else if s.flags&PLUS!=0{out[p]=b'+';p+=1}else if s.flags&SPACE!=0{out[p]=b' ';p+=1}for i in 0..n{out[p+i]=digits[n-1-i]}let len=p+n;if s.flags&ZERO!=0&&s.flags&LEFT==0&&s.precision.is_none()&&s.width>len{let pad=s.width-len;for i in (p..len).rev(){out[i+pad]=out[i]}for i in p..p+pad{out[i]=b'0'}s.width}else{len}}
fn render_unsigned(mut v:u64,base:u64,upper:bool,s:&Spec,out:&mut[u8;MAX_VALUE])->usize{let mut d=[0u8;MAX_VALUE];let mut n=0;loop{let x=(v%base)as u8;d[n]=if x<10{b'0'+x}else{(if upper{b'A'}else{b'a'})+x-10};n+=1;v/=base;if v==0{break}}let min=s.precision.unwrap_or(0);while n<min{d[n]=b'0';n+=1}let mut p=0;if s.flags&ALT!=0{if base==8&&d[n-1]!=b'0'{out[p]=b'0';p+=1}else if base==16{out[p]=b'0';out[p+1]=if upper{b'X'}else{b'x'};p+=2}}for i in 0..n{out[p+i]=d[n-1-i]}let len=p+n;if s.flags&ZERO!=0&&s.flags&LEFT==0&&s.precision.is_none()&&s.width>len{let pad=s.width-len;for i in (p..len).rev(){out[i+pad]=out[i]}for i in p..p+pad{out[i]=b'0'}s.width}else{len}}
fn format_string(value:&[u8],s:&Spec,io:&mut impl Io)->Result<(),()>{let len=s.precision.map_or(value.len(),|p|p.min(value.len()));let pad=s.width.saturating_sub(len);if s.flags&LEFT==0{write_padding(io,pad,if s.flags&ZERO!=0{b'0'}else{b' '})?}write(io,&value[..len])?;if s.flags&LEFT!=0{write_padding(io,pad,b' ')?}Ok(())}
fn write_padding(io:&mut impl Io,mut n:usize,b:u8)->Result<(),()>{while n>0{let take=n.min(PAD_CHUNK.len());if b==b' '{write(io,&PAD_CHUNK[..take])?}else{let z=[b;32];write(io,&z[..take])?}n-=take}Ok(())}
fn write(io:&mut impl Io,b:&[u8])->Result<(),()>{io.write_stdout(b).map_err(|_|())}fn diag(io:&mut impl Io,b:&[u8]){let _=io.write_stderr(b);}

pub struct NativeIo;impl Io for NativeIo{fn write_stdout(&mut self,b:&[u8])->Result<(),Errno>{sunlight_libc::write_all(STDOUT,b)}fn write_stderr(&mut self,b:&[u8])->Result<(),Errno>{sunlight_libc::write_all(STDERR,b)}}

#[cfg(test)]mod tests{extern crate std;use super::*;use std::vec::Vec;struct M{out:Vec<u8>,err:Vec<u8>}impl M{fn new()->Self{Self{out:Vec::new(),err:Vec::new()}}}impl Io for M{fn write_stdout(&mut self,b:&[u8])->Result<(),Errno>{self.out.extend_from_slice(b);Ok(())}fn write_stderr(&mut self,b:&[u8])->Result<(),Errno>{self.err.extend_from_slice(b);Ok(())}}
#[test]fn formats_and_reuses(){let mut m=M::new();assert_eq!(run(&[b"%03d %s\\n",b"7",b"x",b"8",b"y"],&mut m),0);assert_eq!(m.out,b"007 x\n008 y\n");}
#[test]fn b_decodes_and_c_stops(){let mut m=M::new();assert_eq!(run(&[b"%bX",b"a\\nb"],&mut m),0);assert_eq!(m.out,b"a\nbX");let mut m=M::new();assert_eq!(run(&[b"%bX",b"a\\cb"],&mut m),0);assert_eq!(m.out,b"a");}
#[test]fn zero_consumption_does_not_loop(){let mut m=M::new();assert_eq!(run(&[b"%%",b"x"],&mut m),0);assert_eq!(m.out,b"%");}
}
