[package]
name = "sunlight-tasks"
version = "0.2.1320"






















































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-telemetry = { path = "../../sunlight-telemetry" }
sunlight-ui = { path = "../../sunlight-ui", features = ["app"] }
sun-font = { path = "../../sun-font" }

[[bin]]
name = "sunlight-tasks"
path = "src/main.rs"
