[package]
name = "sunlight-tasks"
version = "0.1.555"































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-telemetry = { path = "../../sunlight-telemetry" }
sunlight-ui = { path = "../../sunlight-ui", features = ["app"] }

[[bin]]
name = "sunlight-tasks"
path = "src/main.rs"
