[package]
name = "sunlight-niced"
version = "0.1.483"















































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[[bin]]
name = "niced"
path = "src/main.rs"

[[bin]]
name = "nicectl"
path = "src/bin/nicectl.rs"
