[package]
name = "sunlight-networkd"
version = "0.2.1252"





































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[[bin]]
name = "networkd"
path = "src/main.rs"

[[bin]]
name = "networkctl"
path = "src/bin/networkctl.rs"
