[package]
name = "sunlight-networkd"
version = "0.2.3247-alpha.1"
















































































































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc", features = ["global-alloc"] }
heapless = "0.8"

[[bin]]
name = "networkd"
path = "src/main.rs"

[[bin]]
name = "networkctl"
path = "src/bin/networkctl.rs"
