[package]
name = "sunlightctl"
version = "0.1.498"




























































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[[bin]]
name = "sunlightctl"
path = "src/main.rs"
