[package]
name = "sunlight-init"
version = "0.2.2388-alpha.1"























































































































































































































































































































































































































edition = "2021"

[[bin]]
name = "sunlight-init"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
