[package]
name = "sunlight-init"
version = "0.2.798"























































































































































































































edition = "2021"

[[bin]]
name = "sunlight-init"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
