[package]
name = "sunlight-runner"
version = "0.2.1509"







































































































































































































edition = "2021"

[[bin]]
name = "sunlight-runner"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-ui = { path = "../../sunlight-ui", features = ["app"] }
sun-font = { path = "../../sun-font" }
