[package]
name = "pty_server"
version = "0.2.2141-alpha.1"

































































































































































































































































































edition = "2021"

[[bin]]
name = "pty_server"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
