[package]
name = "sunlight-top"
version = "0.2.4164-alpha.1"






























































































































































































































































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-telemetry = { path = "../sunlight-telemetry" }
