[package]
name = "sun-exec"
version = "0.2.1703"
























































































































































































edition = "2021"

[[bin]]
name = "sun-exec"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
