[package]
name = "sunlight-bench"
version = "0.1.657"



























































edition = "2021"

[[bin]]
name = "sunbench"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-telemetry = { path = "../sunlight-telemetry" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
