[package]
name = "sunlight-bench"
version = "0.2.750"





















































































edition = "2021"

[[bin]]
name = "sunbench"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-telemetry = { path = "../sunlight-telemetry" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
linked_list_allocator = "0.10"
spin = "0.9"
