[package]
name = "sunlight-swapd"
version = "0.2.4352-alpha.2"












































































































































































































edition = "2021"

[[bin]]
name = "sunlight-swapd"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
