[package]
name = "sunlight-swapd"
version = "0.2.3475-alpha.1"









































































































































edition = "2021"

[[bin]]
name = "sunlight-swapd"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
