[package]
name = "cpu-utils"
version = "0.2.3907-alpha.1"





































































































































































































































































































































































































































edition = "2021"

[[bin]]
name = "cpufeat"
path = "src/cpufeat.rs"

[dependencies]
sunlight-libc = { path = "../sunlight-libc" }
