[package]
name = "sunlight-hangman"
version = "0.2.1747"




































































































































































































































































































edition = "2021"

[[bin]]
name = "hangman"
path = "src/main.rs"

[dependencies]
sunlight-libc = { path = "../sunlight-libc" }
