[package]
name = "eyes"
version = "0.2.2353-alpha.1"



























































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }

[[bin]]
name = "eyes"
path = "src/main.rs"
