[package]
name = "sunlight-display"
version = "0.1.600"




























































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-ui = { path = "../../sunlight-ui" }

[[bin]]
name = "sunlight-display"
path = "src/main.rs"
