[package]
name = "sunlight-display"
version = "0.2.1899"















































































































build = "build.rs"































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-libc = { path = "../../sunlight-libc" }
sunlight-ui = { path = "../../sunlight-ui" }
sun-font = { path = "../../sun-font" }

[build-dependencies]
fontdue = "0.7"

[[bin]]
name = "sunlight-display"
path = "src/main.rs"
