[package]
name = "sunlight-edit"
version = "0.2.1025"
























































edition = "2021"

[lib]
name = "sunlight_edit"
path = "src/lib.rs"

[[bin]]
name = "sunlight-edit"
path = "src/main.rs"

[dependencies]
sunlight-dialogs = { path = "../sunlight-dialogs" }
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }

[build-dependencies]
fontdue = "0.7"
