[package]
name = "sunlight-light-lens"
version = "0.2.864"















edition = "2021"

[[bin]]
name = "light-lens"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
