[package]
name = "sunlight-reminders"
version = "0.2.1899"






















































































































edition = "2021"

[[bin]]
name = "sunlight-reminders"
path = "src/main.rs"

[dependencies]
sun-font = { path = "../sun-font" }
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-tz = { path = "../sunlight-tz" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
