[package]
name = "sunlight-timer-server"
version = "0.1.557"











































































































































edition = "2021"

[[bin]]
name = "sunlight-timer-server"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
