[package]
name = "sunlight-files"
version = "0.2.1252"























































































































































edition = "2021"

[[bin]]
name = "sunlight-files"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
