[package]
name = "sunlight-files"
version = "0.2.2176-alpha.1"










































































































































































































































































edition = "2021"

[[bin]]
name = "sunlight-files"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc", features = ["global-alloc"] }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
