[package]
name = "sunlight-ipc"
version = "0.2.2838-alpha.1"





























































































































































































































































































































































































































































edition = "2021"

[dependencies]
