[package]
name = "sunlight-ipc"
version = "0.2.974"


















































































































































































































































edition = "2021"

[dependencies]
