[package]
name = "sunlight-ipc"
version = "0.2.2013"

























































































































































































































































































































































































edition = "2021"

[dependencies]
