[package]
name = "sunlight-vfs-server"
version = "0.1.228"







































































edition = "2021"

[[bin]]
name = "sunlight-vfs-server"
path = "src/main.rs"

[dependencies]
sunlight-fs = { path = "../../sunlight-fs" }
sunlight-ipc = { path = "../../ipc" }
sunlight-fat = { path = "../../sunlight-fat" }
