[package]
name = "sunlight-telemetry"
version = "0.2.1981"









































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../ipc" }

