[package]
name = "sunlight-telemetry"
version = "0.2.3747-alpha.1"
















































































































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../ipc" }

