[package]
name = "sunlightd"
version = "0.2.928"












































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-fs = { path = "../../sunlight-fs" }
heapless = "0.8"

[[bin]]
name = "sunlightd"
path = "src/main.rs"
