[package]
name = "sunlightd"
version = "0.2.3612-alpha.1"
























































































































































































































































































































































































































































































edition = "2021"

[dependencies]
sunlight-ipc = { path = "../../ipc" }
sunlight-fs = { path = "../../sunlight-fs" }
sunlight-libc = { path = "../../sunlight-libc" }
heapless = "0.8"

[lib]
name = "sunlightd"
path = "src/lib.rs"
test = true

[[bin]]
name = "sunlightd"
path = "src/main.rs"
test = false
