[package]
name = "sunlight-dialogs"
version = "0.2.4056-alpha.1"























































































































































































































































































edition = "2021"

[dependencies]
heapless = "0.8"
sunlight-audio = { path = "../sunlight-audio" }
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }

[lib]
name = "sunlight_dialogs"
path = "src/lib.rs"
