[package]
name = "sunlight-dialogs"
version = "0.2.2664-alpha.1"






















































































































































































































edition = "2021"

[dependencies]
heapless = "0.8"

[lib]
name = "sunlight_dialogs"
path = "src/lib.rs"
