[package]
name = "wiseowl-console"
version = "0.2.3937-alpha.1"




















edition = "2021"
publish = false
description = "Wise Owl Graphical Console"

[[bin]]
name = "wiseowl"
path = "src/main.rs"

[features]
conversation-v1-test = []
delegated-session-lifecycle-ipc-v1-test = []

[dependencies]
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc", features = ["global-alloc", "dynamic-heap"] }
sun-font = { path = "../sun-font" }
heapless = "0.8"
wiseowl-brain = { path = "../wiseowl-brain", default-features = false, features = ["sunlightos"] }
