[package]
name = "sunlight-calendar"
version = "0.2.1373"


























































edition = "2021"

[[bin]]
name = "sunlight-calendar"
path = "src/main.rs"

[dependencies]
sunlight-ipc = { path = "../ipc" }
sunlight-libc = { path = "../sunlight-libc" }
sunlight-ui = { path = "../sunlight-ui", features = ["app"] }
sun-font = { path = "../sun-font" }
sunlight-tz = { path = "../sunlight-tz" }
sunlight-locale = { path = "../sunlight-locale" }
sunlight-reminders = { path = "../sunlight-reminders" }

[build-dependencies]
fontdue = "0.7"
